### PR TITLE
add new relion SPA tutorial

### PR DESCRIPTION
**Pull request by azazellochg**
@pconesa could you make sure the link to pdf is correct? :) Also, do you want to to upload the project or you want to save disc space?

### CODE REVIEW

**Comment by pconesa** [comment]
It will be too much for this repo to add the project. It you want we can:

1.- Add just the json
2.- Place the project in our server (same used for tests  datasets)
3.- Have the json contained in the plugin (relion) so Scipion can offer it to users straight away

**Comment by azazellochg** [comment]
I didnt mean to add it here of course, but to the tests data server. Option 3 is actually interesting, I remember you need a templates folder or smth..

**Comment by azazellochg** [comment]
image

**Comment by pconesa** [comment]
You've found the way. For others this is an example:

https://github.com/scipion-em/scipion-em-facilities/tree/devel/emfacilities/templates

**Pull request merged**
